### PR TITLE
design : Channel Page UI markup

### LINKED ISSUE #49: design : Channel Page UI markup

### PR DESCRIPTION
**Pull request by ag502**
Resolved #49

### CODE REVIEW

**Comment by ag502** [comment]
시간나실때 피드백 남겨 주시면 감사하겠습니다.

https://61d257a71897c4003a50a451-ukusptswup.chromatic.com/?path=/story/page-channelpage--channel-page-story

**Review by Chaehui-Seo — APPROVED** [review]
LGTM!

**Review by kmswlee — APPROVED** [review]
LGTM~ 😄

**Review by kimhanui — APPROVED** [review]
LGTM!

**Pull request merged**
